"""
Django settings for Student project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z^k7_antk*z#1@ohb-#*7r$opf7l37)b_0%ntqz=_36$69g=7o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'students', #student app added
    'rest_framework', #Restfrmework added
    'rest_framework_simplejwt', #for localizations/translations
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    "django_celery_beat", 
    # 'django_celery_results',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Student.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Student.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "student_db",
        "USER": "student_user",
        "PASSWORD": "20141893613",
        "HOST": "localhost",
        "PORT": "3306",

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
        ],
    
    'DEFAULT_RENDERER_CLASSES': [
        'students.renderers.CustomRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],

# Global pagination
    # 'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    # 'DEFAULT_VERSION': 'v1',
    # 'ALLOWED_VERSIONS': ['v1', 'v2'],
    # 'VERSION_PARAM': 'version',

    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 3,

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated' # Protects EVERYTHING by default
    ]

}

#JWT config - customize token behaviour
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True, 
}
# Configure Redis 
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0", # db 0
        # LOCATION format: redis://host:port/db_number

    'OPTIONS':{
        # Options monitors the behaviour of the cache
        'CLIENT_CLASS': 'django_redis.client.DefaultClient', #Use the standard Redis client.
        'SOCKET_CONNECT_TIMEOUT': 5,  # maximum time allowed to establish a connection, before connection fails
        'SOCKET_TIMEOUT': 5, # maximum time for a command after the connection has already been made.
        'IGNORE_EXCEPTIONS': True,  # CRITICAL: if Redis is down, fall back gracefully
            # WHY IGNORE_EXCEPTIONS=True? Redis is a cache — a luxury, not a requirement.
            # If Redis goes down, your app should still work (slower, from DB).
            # Without this, a Redis outage takes down your entire API.
    },

    'KEY_PREFIX': 'student_api',
    # A string that will be automatically included (prepended by default) to all cache keys used by the Django server
    #django can store as: student_api:departments and wont conflict another project name
    # Another project stores ecommerce:departments
    }
}
# Django's built-in SMTP backend.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default='smtp.gmail.com')
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='darajanwogu@gmail.com')
DEFAULT_FROM_NAME = config('DEFAULT_FROM_NAME', default='Student API')

# Connection timeout in seconds
# WHY? SMTP servers can be slow. Without a timeout, a hung connection
# blocks your worker forever. 10 seconds is a reasonable ceiling.
EMAIL_TIMEOUT = 10

CELERY_BROKER_URL = "redis://127.0.0.1:6379/1"    # ← db 1 = BROKER
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/2" # ← db 2 = TASK RESULTS

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "send-all-students": {
        "task": "students.tasks.send_email_to_all_students",
        "schedule": crontab(minute="*/1"), #rontab(minute="*/5") means send every 5mi
    },

    "birthday-emails": {
        "task": "students.tasks.send_birthday_emails",
        "schedule": crontab(hour=9, minute=45), #send birthday email by 8:00
    },

    "math-course-emails": {
        "task": "students.tasks.send_math_students_email",
        "schedule": crontab(hour=12, minute=0), #sends by 9:00
    },
}

COUNTRIES_API_BASE_URL = config("COUNTRIES_API_BASE_URL")
COUNTRIES_API_KEY = config("COUNTRIES_API_KEY")
