# Generated by Django 5.0.7 on 2026-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(max_length=20),
        ),
    ]
