# Generated by Django 6.0.5 on 2026-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_department_alter_student_age_student_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(blank=True, to="students.course"),
        ),
    ]
